[package]
name = "rudim"
version = "0.1.0"
authors = ["Dion Dokter <diondokter@gmail.com>"]
edition = "2018"

[lib]
name = "rudim"
path = "src/lib.rs"

[[bin]]
name = "rudim-r"
path = "src/main.rs"

[dependencies]
log = "0.4"
simple_logger = "1.6"